### ISSUE TITLE
1.2 broken with Preact?

### ISSUE THREAD

**Issue by zgoda** [JoviDeCroock/hoofd#38]
I'm getting

```console
⚠ WARN ../node_modules/hoofd/preact/dist/hoofd.module.js 158:24-37
"export 'createContext' was not found in 'preact/hooks'
 @ ./components/app.tsx
 @ ./index.ts
 @ ../node_modules/preact-cli/lib/lib/entry.js
```

in terminal, and

```
Uncaught TypeError: Object(...) is not a function
    at eval (index.ts?ddd1:250)
    at Module.../node_modules/hoofd/preact/dist/hoofd.module.js (bundle.js:941)
    at __webpack_require__ (bundle.js:790)
    at fn (bundle.js:101)
    at eval (app.tsx?7666:1)
    at Module../components/app.tsx (bundle.js:1353)
    at __webpack_require__ (bundle.js:790)
    at fn (bundle.js:101)
    at eval (index.ts?a959:1)
    at Module../index.ts (bundle.js:1365)
```

in Chrome devtools console.

Code:

```typescript
function App(): JSX.Element {
  useLang('en');
  useTitle('Application');
  useMeta({ name: 'Author', content: 'Jarek Zgoda' });
  return (
    <div class="container grid-md">
      <h1>Application</h1>
    </div>
  );
}
```

This works fine with hoofd 1.1.

**Comment by JoviDeCroock** [comment]
Oh, you're right 😅 a fix would probably be to create a file that does the following:

```js
export { useState, useRef, useMemo, useEffect } from 'preact/hooks';
export { createContext } from 'preact';
```

Rather than just aliassing to `preact/hooks` this because 1.2 introduces support for concurrent rendering, completely overlooked this, apologies.
